# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: false

env:
 global:
   - CRAN: http://cran.rstudio.com
   - WARNINGS_ARE_ERRORS=1
   - R_BUILD_ARGS=--no-manual
   - R_CHECK_ARGS=--no-manual --as-cran

r_github_packages:
  - Rexamine/stringi

notifications:
  email:
    on_success: change
    on_failure: change
